#!/usr/bin/env python3
import pandas as pd
from gtfparse import read_gtf
import sys
import os

reference={}
ctrf = sys.argv[1]; ctr = open(ctrf).read(); exec(ctr)

df = read_gtf(annotation)
gene_type = list(set(df["gene_biotype"]))
print("You can select the following gene type: ")
print("\n")
num = 1
for i in gene_type:
    if i !="":
        print(str(num)+"\t"+i); num = num + 1

select_type = input("Select the gene type listed above: ")

select_gene = list(df[(df["feature"] == "gene") & (df["gene_biotype"] == select_type)]["gene_id"])
age_out = os.path.join(outpath, age + "." + select_type)

original_age = os.path.join(outpath, age)

age = pd.read_csv(original_age, sep="\t")
protein_age = age[age["Gene"].isin(select_gene) & (age["GeneMaskRatio"]<0.7) & (age["Confidence"]=="CON")]
protein_age.to_csv(age_out, sep="\t", index=False)
print("\n")
print("Your output is stored in {0}".format(age_out))
